# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

parameters:
    app.domain: '%env(string:DOMAIN)%'
    app.redirect_after_success_payment: '%env(string:REDIRECT_AFTER_SUCCESS_PAYMENT)%'
    app.redirect_after_failure_payment: '%env(string:REDIRECT_AFTER_FAILURE_PAYMENT)%'
    
    app.paypal_sandbox: '%env(bool:PAYPAL_SANDBOX)%'
    app.paypal_sandbox_api_url: '%env(string:PAYPAL_API_SANDBOX_URL)%'
    app.paypal_account_sandbox: '%env(string:PAYPAL_ACCOUNT_SANDBOX)%'
    app.paypal_account_sandbox_secret: '%env(string:PAYPAL_ACCOUNT_SANDBOX_SECRET)%'
    app.paypal_api_url: '%env(string:PAYPAL_API_URL)%'
    
    app.adyen_sandbox: '%env(bool:ADYEN_SANDBOX)%'
    app.adyen_account_sandbox: '%env(string:ADYEN_ACCOUNT_SANDBOX)%'
    app.adyen_account_sandbox_secret: '%env(string:ADYEN_ACCOUNT_SANDBOX_SECRET)%'