nelmio_api_doc:
    documentation:
        servers:
          - url: https://ptgr.localhost
        info:
            title: Payment microservice
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
